// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_250k_score = "CgkI2fT3yu8SEAIQDA"; // <GPGSID>
        public const string achievement_200k_score = "CgkI2fT3yu8SEAIQCw"; // <GPGSID>
        public const string achievement_150k_score = "CgkI2fT3yu8SEAIQCQ"; // <GPGSID>
        public const string achievement_100k_score = "CgkI2fT3yu8SEAIQBw"; // <GPGSID>
        public const string achievement_15m_score = "CgkI2fT3yu8SEAIQEg"; // <GPGSID>
        public const string achievement_175k_score = "CgkI2fT3yu8SEAIQCg"; // <GPGSID>
        public const string achievement_125k_score = "CgkI2fT3yu8SEAIQCA"; // <GPGSID>
        public const string achievement_10m_score = "CgkI2fT3yu8SEAIQEQ"; // <GPGSID>
        public const string achievement_50k_score = "CgkI2fT3yu8SEAIQBg"; // <GPGSID>
        public const string achievement_5k_score = "CgkI2fT3yu8SEAIQBQ"; // <GPGSID>
        public const string achievement_5m_score = "CgkI2fT3yu8SEAIQEA"; // <GPGSID>
        public const string achievement_400k_score = "CgkI2fT3yu8SEAIQDg"; // <GPGSID>
        public const string achievement_1m_score = "CgkI2fT3yu8SEAIQDw"; // <GPGSID>
        public const string achievement_300k_score = "CgkI2fT3yu8SEAIQDQ"; // <GPGSID>
        public const string achievement_100m_score = "CgkI2fT3yu8SEAIQFA"; // <GPGSID>
        public const string achievement_25m_score = "CgkI2fT3yu8SEAIQEw"; // <GPGSID>

}

